pub mod auth;
pub mod message;
pub mod room;
pub mod connection;
pub mod search;
pub mod push;
pub mod bot;
pub mod setup;
pub mod demo;
pub mod optimized_connection;
pub mod cache;
pub mod cached_auth;
pub mod cached_room;
pub mod cached_message;
pub mod cached_search;
pub mod cache_manager;

pub use auth::AuthService;
pub use message::{MessageService, MessageServiceTrait};
pub use room::RoomService;
pub use connection::ConnectionManager;
pub use search::{SearchService, SearchServiceTrait};
pub use push::{PushNotificationService, PushNotificationServiceImpl, VapidConfig};
pub use bot::{BotService, BotServiceImpl};
pub use setup::{SetupService, SetupServiceImpl};
pub use demo::{DemoServiceTrait, DemoServiceImpl, DemoUserCredential, DemoIntegrityStatus, SimulationSession, TourStep, DemoStatistics};
pub use optimized_connection::OptimizedConnectionManager;
pub use cache::{CacheService, CacheServiceTrait, CacheStats, CacheError};
pub use cached_auth::CachedAuthService;
pub use cached_room::CachedRoomService;
pub use cached_message::CachedMessageService;
pub use cached_search::CachedSearchService;
pub use cache_manager::{CacheManager, CacheManagerFactory, CacheHealthStatus, CacheHealth};