blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/that-in-rust/campfire-on-rust/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/that-in-rust/campfire-on-rust/tree/main/docs
    about: Check the documentation for guides and API reference